np_news_homepage:
    pattern:  /
    defaults: { _controller: NpNewsBundle:Default:index }
np_news_pull:
    pattern:  /admin/pull
    defaults: { _controller: NpNewsBundle:Default:pull }
NpNewsBundle_admin_feeds:
    resource: "@NpNewsBundle/Resources/config/routing/feed.yml"
    prefix:   /admin/feeds