<?php

namespace Np\NewsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FeedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedRepository extends EntityRepository
{
    /**
     * Get all origin posts as entities
     *
     * @return array
     */
    private function getItemCandidates()
    {
        $feeds = $this->findAll();
        $itemsCandidates = array();
        foreach ($feeds as $feed) {
            $itemsCandidates = array_merge($feed->getItemCandidates(), $itemsCandidates);
            $feed->setLastPullTime($_SERVER['REQUEST_TIME']);
        }
        $this->getEntityManager()->flush();
        return $itemsCandidates;
    }

    /**
     * Update feeds from origins
     */
    public function pull()
    {
        $itemsCandidates = $this->getItemCandidates();

        if (count($itemsCandidates)) {
            $amountAdded = $this->getEntityManager()->getRepository('NpNewsBundle:FeedItem')->mergeItemCandidates($itemsCandidates);
        } else {
            $amountAdded = 0;
        }
        return $amountAdded;
    }
}
