<?php

namespace Np\NewsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FeedItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedItemRepository extends EntityRepository
{
    /**
     * Check if item is unique
     *
     * @param FeedItem $item
     * @return bool
     */
    private function isItemUnique(FeedItem $item)
    {
        $suggestions = $this->findBy(array('url' => $item->getUrl()));
        return !count($suggestions);
    }

    /**
     * Save new items
     *
     * @param array $itemCandidates
     * @return int
     */
    public function mergeItemCandidates(array $itemCandidates)
    {
        $amountAdded = 0;
        foreach ($itemCandidates as $itemCandidate) {
            if ($this->isItemUnique($itemCandidate)) {
                $amountAdded ++;
                $this->getEntityManager()->persist($itemCandidate);
            }
        }
        $this->getEntityManager()->flush();
        return $amountAdded;
    }
}